WITH RECURSIVE 대장균_GEN AS (

    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT 자식.ID, 자식.PARENT_ID, 부모.GEN + 1
    FROM 대장균_GEN AS 부모 JOIN ECOLI_DATA AS 자식 ON 부모.ID = 자식.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GEN
FROM 대장균_GEN
WEHRE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GEN
ORDER BY GEN ASC;


